version: "3.9"
services:
  sql-server:
    container_name: sql-server
    user: root
    hostname: sqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_USER=admin
      - MSSQL_SA_PASSWORD=Ubunchuu@2022
    volumes:
      - ./sql:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
